name: Build Windows EXE and attach to Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'   # ex: v1.0.0

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      # Build optimized EXE (one file, no console window)
      - name: PyInstaller build
        run: |
          pyinstaller --onefile --noconsole ^
            --name AntiDrowsePRO ^
            anti_drowse_pro.py

      - name: Upload artifact (for debugging/download)
        uses: actions/upload-artifact@v4
        with:
          name: AntiDrowsePRO-windows
          path: dist/AntiDrowsePRO.exe

      # If it's a tag (v*), attach the EXE to a GitHub Release
      - name: Create/Upload Release asset
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/AntiDrowsePRO.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
